build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Morgan Jones - QA Lead"
    email: "morgan@eazybank.com"
  onCallSupport:
    - (718) 159-6352
    - (718) 951-7458
