spring:
  application:
    name: "configserver"
  profiles:
    active: git
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlirezaMohamadian1998/eazybytes-config.git
          clone-on-start: true
          default-label: main
          timeout: 5
          force-pull: true
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///C:/Users/alire/JetBrainWorkplace/udemyTutorial/Microservices/section 6/config"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071
